In [14]:
import pandas as pd
from sklearn import tree
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler

In [7]:
x = np.genfromtxt('poker-hand-training-true.data', delimiter=',',dtype=None)
y = np.genfromtxt('poker-hand-testing.data', delimiter=',',dtype=None)

x_train = x[0:,0:10]
y_train = x[0:,10]

x_test = y[0:,0:10]
y_test = y[0:,10]

In [8]:
clf = tree.DecisionTreeClassifier()
clf.fit(X=x_train, y=y_train)
clf.feature_importances_ # [ 1.,  0.,  0.]
clf.score(X=x_test, y=y_test) # 1.0

0.47832999999999998

In [15]:
data_train = pd.read_csv(filepath_or_buffer="poker-hand-training-true.data", sep=',', header=None)
data_test = pd.read_csv(filepath_or_buffer="poker-hand-testing.data", sep=',', header=None)
#----------------------------------------------------------------
#Print it's Shape to get an idea of the data set:
#----------------------------------------------------------------
print(data_train.shape)
print(data_test.shape)
#----------------------------------------------------------------
#Prepare the Data for Training and Testing:
#----------------------------------------------------------------
#Ready the Train Data
array_train = data_train.values
data_train = array_train[:,0:10]
label_train = array_train[:,10]
#Ready the Test Data
array_test = data_test.values
data_test = array_test[:,0:10]
label_test = array_test[:,10]

(25010, 11)
(1000000, 11)


In [16]:
#----------------------------------------------------------------
# Scaling the Data for our Main Model
#----------------------------------------------------------------
# Scale the Data to Make the NN easier to converge
scaler = StandardScaler()
# Fit only to the training data
scaler.fit(data_train)  
# Transform the training and testing data
data_train = scaler.transform(data_train)
data_test = scaler.transform(data_test)
#----------------------------------------------------------------
#Apply the MLPClassifier:
#----------------------------------------------------------------
acc_array = [0] * 5
for s in range (1,6):
    #Init MLPClassifier
    clf = MLPClassifier(solver='adam', alpha=1e-5,hidden_layer_sizes=(64,64),
                        activation='tanh', learning_rate_init=0.02,max_iter=2000,random_state=s)
    #Fit the Model
    result = clf.fit(data_train, label_train)
    #Predict
    prediction = clf.predict(data_test)
    #Get Accuracy
    acc = accuracy_score(label_test, prediction)
    #Store in the Array
    acc_array[s-1] = acc
#----------------------------------------------------------------
#Fetch & Print the Results:
#----------------------------------------------------------------
    print(classification_report(label_test,prediction))
    print("Accuracy using MLPClassifier and Random Seed:",s,":",str(acc)) 
    print(confusion_matrix(label_test, prediction))
print("Mean Accuracy using MLPClassifier Classifier: ",np.array(acc_array).mean())

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)


             precision    recall  f1-score   support

          0       0.97      0.99      0.98    501209
          1       0.97      0.96      0.97    422498
          2       0.87      0.79      0.83     47622
          3       0.82      0.81      0.82     21121
          4       0.26      0.09      0.14      3885
          5       0.22      0.14      0.17      1996
          6       0.72      0.39      0.50      1424
          7       0.26      0.05      0.09       230
          8       0.00      0.00      0.00        12
          9       0.00      0.00      0.00         3

avg / total       0.96      0.96      0.96   1000000

Accuracy using MLPClassifier and Random Seed: 1 : 0.957466
[[494728   4778      0      0    488    799      0      0    391     25]
 [ 12774 406728   1605    136    508    200      1      0    530     16]
 [    24   7103  37591   2815      1      0     83      5      0      0]
 [     0     79   3718  17208      0      0     86     30      0      0]
 [  3259  

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


             precision    recall  f1-score   support

          0       0.99      1.00      0.99    501209
          1       0.99      1.00      0.99    422498
          2       0.92      0.96      0.94     47622
          3       0.92      0.81      0.86     21121
          4       0.66      0.09      0.17      3885
          5       0.45      0.07      0.12      1996
          6       0.56      0.60      0.58      1424
          7       0.12      0.03      0.05       230
          8       0.00      0.00      0.00        12
          9       0.00      0.00      0.00         3

avg / total       0.98      0.98      0.98   1000000

Accuracy using MLPClassifier and Random Seed: 3 : 0.984232
[[499381   1486      0      0    176    134      0      0     32      0]
 [  1275 420721    375      0     14     32      1      0     80      0]
 [     0   1131  45764    678      0      0     44      5      0      0]
 [     0      0   3524  17003      0      0    549     45      0      0]
 [  3407  